// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: qFgf32neWRE8gRveVBaatz
// Component: wOG229KbexC2

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import "@plasmicapp/react-web/lib/plasmic.css";

import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import plasmic_plasmic_rich_components_css from "../plasmic_rich_components/plasmic.module.css"; // plasmic-import: jkU633o1Cz7HrJdwdxhVHk/projectcss
import projectcss from "./plasmic.module.css"; // plasmic-import: qFgf32neWRE8gRveVBaatz/projectcss
import sty from "./PlasmicPercentageBadge.module.css"; // plasmic-import: wOG229KbexC2/css

import Icon44Icon from "./icons/PlasmicIcon__Icon44"; // plasmic-import: 98WwP0TnXJrP/icon

createPlasmicElementProxy;

export type PlasmicPercentageBadge__VariantMembers = {
  negative: "negative";
};
export type PlasmicPercentageBadge__VariantsArgs = {
  negative?: SingleBooleanChoiceArg<"negative">;
};
type VariantPropType = keyof PlasmicPercentageBadge__VariantsArgs;
export const PlasmicPercentageBadge__VariantProps = new Array<VariantPropType>(
  "negative"
);

export type PlasmicPercentageBadge__ArgsType = {
  onNegativeChange?: (val: any) => void;
  percentageChange?: React.ReactNode;
};
type ArgPropType = keyof PlasmicPercentageBadge__ArgsType;
export const PlasmicPercentageBadge__ArgProps = new Array<ArgPropType>(
  "onNegativeChange",
  "percentageChange"
);

export type PlasmicPercentageBadge__OverridesType = {
  percentageBadge?: Flex__<"div">;
  svg?: Flex__<"svg">;
};

export interface DefaultPercentageBadgeProps {
  onNegativeChange?: (val: any) => void;
  percentageChange?: React.ReactNode;
  negative?: SingleBooleanChoiceArg<"negative">;
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicPercentageBadge__RenderFunc(props: {
  variants: PlasmicPercentageBadge__VariantsArgs;
  args: PlasmicPercentageBadge__ArgsType;
  overrides: PlasmicPercentageBadge__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const $translator = usePlasmicTranslator?.();

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const stateSpecs: Parameters<typeof useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "negative",
        type: "writable",
        variableType: "variant",

        valueProp: "negative",
        onChangeProp: "onNegativeChange"
      }
    ],
    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $refs
  });

  return (
    <Stack__
      as={"div"}
      data-plasmic-name={"percentageBadge"}
      data-plasmic-override={overrides.percentageBadge}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      hasGap={true}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        plasmic_antd_5_hostless_css.plasmic_tokens,
        plasmic_plasmic_rich_components_css.plasmic_tokens,
        sty.percentageBadge
      )}
    >
      {renderPlasmicSlot({
        defaultContents: <Trans__>{"+0.00%"}</Trans__>,
        value: args.percentageChange,
        className: classNames(sty.slotTargetPercentageChange, {
          [sty.slotTargetPercentageChangenegative]: hasVariant(
            $state,
            "negative",
            "negative"
          )
        })
      })}
      <Icon44Icon
        data-plasmic-name={"svg"}
        data-plasmic-override={overrides.svg}
        className={classNames(projectcss.all, sty.svg, {
          [sty.svgnegative]: hasVariant($state, "negative", "negative")
        })}
        role={"img"}
      />
    </Stack__>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  percentageBadge: ["percentageBadge", "svg"],
  svg: ["svg"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  percentageBadge: "div";
  svg: "svg";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicPercentageBadge__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicPercentageBadge__VariantsArgs;
    args?: PlasmicPercentageBadge__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicPercentageBadge__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicPercentageBadge__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicPercentageBadge__ArgProps,
          internalVariantPropNames: PlasmicPercentageBadge__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicPercentageBadge__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "percentageBadge") {
    func.displayName = "PlasmicPercentageBadge";
  } else {
    func.displayName = `PlasmicPercentageBadge.${nodeName}`;
  }
  return func;
}

export const PlasmicPercentageBadge = Object.assign(
  // Top-level PlasmicPercentageBadge renders the root element
  makeNodeComponent("percentageBadge"),
  {
    // Helper components rendering sub-elements
    svg: makeNodeComponent("svg"),

    // Metadata about props expected for PlasmicPercentageBadge
    internalVariantProps: PlasmicPercentageBadge__VariantProps,
    internalArgProps: PlasmicPercentageBadge__ArgProps
  }
);

export default PlasmicPercentageBadge;
/* prettier-ignore-end */
