// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: qFgf32neWRE8gRveVBaatz
// Component: CjCWQ83VlxB3

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import CtCheckbox from "../../CtCheckbox"; // plasmic-import: h4AhLHpwZjUP/component
import CtSorting from "../../CtSorting"; // plasmic-import: LtnGs58PcPwQ/component
import CtInfoIcon from "../../CtInfoIcon"; // plasmic-import: g9gKYSYktTlZ/component

import "@plasmicapp/react-web/lib/plasmic.css";

import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import plasmic_plasmic_rich_components_css from "../plasmic_rich_components/plasmic.module.css"; // plasmic-import: jkU633o1Cz7HrJdwdxhVHk/projectcss
import projectcss from "./plasmic.module.css"; // plasmic-import: qFgf32neWRE8gRveVBaatz/projectcss
import sty from "./PlasmicCtHeader.module.css"; // plasmic-import: CjCWQ83VlxB3/css

createPlasmicElementProxy;

export type PlasmicCtHeader__VariantMembers = {};
export type PlasmicCtHeader__VariantsArgs = {};
type VariantPropType = keyof PlasmicCtHeader__VariantsArgs;
export const PlasmicCtHeader__VariantProps = new Array<VariantPropType>();

export type PlasmicCtHeader__ArgsType = {
  noData?: string;
  headerCheckboxSection2?: React.ReactNode;
};
type ArgPropType = keyof PlasmicCtHeader__ArgsType;
export const PlasmicCtHeader__ArgProps = new Array<ArgPropType>(
  "noData",
  "headerCheckboxSection2"
);

export type PlasmicCtHeader__OverridesType = {
  header?: Flex__<"section">;
  headerCheckboxSection?: Flex__<"section">;
  labelSection?: Flex__<"div">;
  line?: Flex__<"div">;
  text?: Flex__<"div">;
  ctSorting?: Flex__<typeof CtSorting>;
  ctInfoIcon?: Flex__<typeof CtInfoIcon>;
  headerMoreSection?: Flex__<"section">;
};

export interface DefaultCtHeaderProps {
  noData?: string;
  headerCheckboxSection2?: React.ReactNode;
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicCtHeader__RenderFunc(props: {
  variants: PlasmicCtHeader__VariantsArgs;
  args: PlasmicCtHeader__ArgsType;
  overrides: PlasmicCtHeader__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const $translator = usePlasmicTranslator?.();

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  return (
    <section
      data-plasmic-name={"header"}
      data-plasmic-override={overrides.header}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        plasmic_antd_5_hostless_css.plasmic_tokens,
        plasmic_plasmic_rich_components_css.plasmic_tokens,
        sty.header
      )}
    >
      <section
        data-plasmic-name={"headerCheckboxSection"}
        data-plasmic-override={overrides.headerCheckboxSection}
        className={classNames(projectcss.all, sty.headerCheckboxSection)}
      >
        {renderPlasmicSlot({
          defaultContents: (
            <CtCheckbox
              aria-label={"Primary"}
              isDisabled={(() => {
                try {
                  return $props.noData === true;
                } catch (e) {
                  if (
                    e instanceof TypeError ||
                    e?.plasmicType === "PlasmicUndefinedDataError"
                  ) {
                    return "isDisabled";
                  }
                  throw e;
                }
              })()}
              isIndeterminate={(() => {
                try {
                  return (() => {
                    const checkedCount = $state.secondaryCheckbox.filter(
                      cb => cb.isChecked
                    ).length;
                    const totalCount = $state.secondaryCheckbox.length;
                    return checkedCount > 0 && checkedCount < totalCount;
                  })();
                } catch (e) {
                  if (
                    e instanceof TypeError ||
                    e?.plasmicType === "PlasmicUndefinedDataError"
                  ) {
                    return [];
                  }
                  throw e;
                }
              })()}
            />
          ),

          value: args.headerCheckboxSection2
        })}
      </section>
      <Stack__
        as={"div"}
        data-plasmic-name={"labelSection"}
        data-plasmic-override={overrides.labelSection}
        hasGap={true}
        className={classNames(projectcss.all, sty.labelSection)}
      >
        <div
          data-plasmic-name={"line"}
          data-plasmic-override={overrides.line}
          className={classNames(projectcss.all, sty.line)}
        />

        <div
          data-plasmic-name={"text"}
          data-plasmic-override={overrides.text}
          className={classNames(
            projectcss.all,
            projectcss.__wab_text,
            sty.text
          )}
        >
          <Trans__>{"Name"}</Trans__>
        </div>
        <CtSorting
          data-plasmic-name={"ctSorting"}
          data-plasmic-override={overrides.ctSorting}
          className={classNames("__wab_instance", sty.ctSorting)}
        />

        <CtInfoIcon
          data-plasmic-name={"ctInfoIcon"}
          data-plasmic-override={overrides.ctInfoIcon}
          className={classNames("__wab_instance", sty.ctInfoIcon)}
        />
      </Stack__>
      <section
        data-plasmic-name={"headerMoreSection"}
        data-plasmic-override={overrides.headerMoreSection}
        className={classNames(projectcss.all, sty.headerMoreSection)}
      />
    </section>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  header: [
    "header",
    "headerCheckboxSection",
    "labelSection",
    "line",
    "text",
    "ctSorting",
    "ctInfoIcon",
    "headerMoreSection"
  ],
  headerCheckboxSection: ["headerCheckboxSection"],
  labelSection: ["labelSection", "line", "text", "ctSorting", "ctInfoIcon"],
  line: ["line"],
  text: ["text"],
  ctSorting: ["ctSorting"],
  ctInfoIcon: ["ctInfoIcon"],
  headerMoreSection: ["headerMoreSection"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  header: "section";
  headerCheckboxSection: "section";
  labelSection: "div";
  line: "div";
  text: "div";
  ctSorting: typeof CtSorting;
  ctInfoIcon: typeof CtInfoIcon;
  headerMoreSection: "section";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicCtHeader__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicCtHeader__VariantsArgs;
    args?: PlasmicCtHeader__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicCtHeader__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicCtHeader__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicCtHeader__ArgProps,
          internalVariantPropNames: PlasmicCtHeader__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicCtHeader__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "header") {
    func.displayName = "PlasmicCtHeader";
  } else {
    func.displayName = `PlasmicCtHeader.${nodeName}`;
  }
  return func;
}

export const PlasmicCtHeader = Object.assign(
  // Top-level PlasmicCtHeader renders the root element
  makeNodeComponent("header"),
  {
    // Helper components rendering sub-elements
    headerCheckboxSection: makeNodeComponent("headerCheckboxSection"),
    labelSection: makeNodeComponent("labelSection"),
    line: makeNodeComponent("line"),
    text: makeNodeComponent("text"),
    ctSorting: makeNodeComponent("ctSorting"),
    ctInfoIcon: makeNodeComponent("ctInfoIcon"),
    headerMoreSection: makeNodeComponent("headerMoreSection"),

    // Metadata about props expected for PlasmicCtHeader
    internalVariantProps: PlasmicCtHeader__VariantProps,
    internalArgProps: PlasmicCtHeader__ArgProps
  }
);

export default PlasmicCtHeader;
/* prettier-ignore-end */
