// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: qFgf32neWRE8gRveVBaatz
// Component: VUxalQKdyCYj

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import ActionListItems from "../../ActionListItems"; // plasmic-import: _msz16lTRhj1/component

import "@plasmicapp/react-web/lib/plasmic.css";

import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import plasmic_plasmic_rich_components_css from "../plasmic_rich_components/plasmic.module.css"; // plasmic-import: jkU633o1Cz7HrJdwdxhVHk/projectcss
import projectcss from "./plasmic.module.css"; // plasmic-import: qFgf32neWRE8gRveVBaatz/projectcss
import sty from "./PlasmicActionsList.module.css"; // plasmic-import: VUxalQKdyCYj/css

createPlasmicElementProxy;

export type PlasmicActionsList__VariantMembers = {
  noTitle: "noTitle";
};
export type PlasmicActionsList__VariantsArgs = {
  noTitle?: SingleBooleanChoiceArg<"noTitle">;
};
type VariantPropType = keyof PlasmicActionsList__VariantsArgs;
export const PlasmicActionsList__VariantProps = new Array<VariantPropType>(
  "noTitle"
);

export type PlasmicActionsList__ArgsType = {
  dropdownTitle?: React.ReactNode;
  actionsList?: React.ReactNode;
};
type ArgPropType = keyof PlasmicActionsList__ArgsType;
export const PlasmicActionsList__ArgProps = new Array<ArgPropType>(
  "dropdownTitle",
  "actionsList"
);

export type PlasmicActionsList__OverridesType = {
  dropdown?: Flex__<"div">;
  title?: Flex__<"div">;
  actions?: Flex__<"div">;
};

export interface DefaultActionsListProps {
  dropdownTitle?: React.ReactNode;
  actionsList?: React.ReactNode;
  noTitle?: SingleBooleanChoiceArg<"noTitle">;
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicActionsList__RenderFunc(props: {
  variants: PlasmicActionsList__VariantsArgs;
  args: PlasmicActionsList__ArgsType;
  overrides: PlasmicActionsList__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const $translator = usePlasmicTranslator?.();

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const stateSpecs: Parameters<typeof useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "noTitle",
        type: "private",
        variableType: "variant",
        initFunc: ({ $props, $state, $queries, $ctx }) => $props.noTitle
      }
    ],
    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $refs
  });

  return (
    <Stack__
      as={"div"}
      data-plasmic-name={"dropdown"}
      data-plasmic-override={overrides.dropdown}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      hasGap={true}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        plasmic_antd_5_hostless_css.plasmic_tokens,
        plasmic_plasmic_rich_components_css.plasmic_tokens,
        sty.dropdown,
        { [sty.dropdownnoTitle]: hasVariant($state, "noTitle", "noTitle") }
      )}
    >
      {(() => {
        try {
          return !$state.noTitle;
        } catch (e) {
          if (
            e instanceof TypeError ||
            e?.plasmicType === "PlasmicUndefinedDataError"
          ) {
            return false;
          }
          throw e;
        }
      })() ? (
        <div
          data-plasmic-name={"title"}
          data-plasmic-override={overrides.title}
          className={classNames(projectcss.all, sty.title, {
            [sty.titlenoTitle]: hasVariant($state, "noTitle", "noTitle")
          })}
        >
          {renderPlasmicSlot({
            defaultContents: <Trans__>{"Dropdown Title"}</Trans__>,
            value: args.dropdownTitle,
            className: classNames(sty.slotTargetDropdownTitle)
          })}
        </div>
      ) : null}
      <Stack__
        as={"div"}
        data-plasmic-name={"actions"}
        data-plasmic-override={overrides.actions}
        hasGap={true}
        className={classNames(projectcss.all, sty.actions)}
      >
        {renderPlasmicSlot({
          defaultContents: (
            <React.Fragment>
              <ActionListItems
                className={classNames(
                  "__wab_instance",
                  sty.actionListItems__gXuZl
                )}
              />

              <ActionListItems
                className={classNames(
                  "__wab_instance",
                  sty.actionListItems__hl7Sa
                )}
              />
            </React.Fragment>
          ),
          value: args.actionsList
        })}
      </Stack__>
    </Stack__>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  dropdown: ["dropdown", "title", "actions"],
  title: ["title"],
  actions: ["actions"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  dropdown: "div";
  title: "div";
  actions: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicActionsList__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicActionsList__VariantsArgs;
    args?: PlasmicActionsList__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicActionsList__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicActionsList__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicActionsList__ArgProps,
          internalVariantPropNames: PlasmicActionsList__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicActionsList__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "dropdown") {
    func.displayName = "PlasmicActionsList";
  } else {
    func.displayName = `PlasmicActionsList.${nodeName}`;
  }
  return func;
}

export const PlasmicActionsList = Object.assign(
  // Top-level PlasmicActionsList renders the root element
  makeNodeComponent("dropdown"),
  {
    // Helper components rendering sub-elements
    title: makeNodeComponent("title"),
    actions: makeNodeComponent("actions"),

    // Metadata about props expected for PlasmicActionsList
    internalVariantProps: PlasmicActionsList__VariantProps,
    internalArgProps: PlasmicActionsList__ArgProps
  }
);

export default PlasmicActionsList;
/* prettier-ignore-end */
