// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: qFgf32neWRE8gRveVBaatz
// Component: RX5xG043iUMC

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import Dashboard from "../../Dashboard"; // plasmic-import: xrHIipmjGkuW/component
import PageInfo from "../../PageInfo"; // plasmic-import: -5yQM3hZscI3/component
import Button from "../../Button"; // plasmic-import: JRPPbMhYptfo/component
import CustomTable from "../../CustomTable"; // plasmic-import: SyYLCRWlXb0u/component

import "@plasmicapp/react-web/lib/plasmic.css";

import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import plasmic_plasmic_rich_components_css from "../plasmic_rich_components/plasmic.module.css"; // plasmic-import: jkU633o1Cz7HrJdwdxhVHk/projectcss
import projectcss from "./plasmic.module.css"; // plasmic-import: qFgf32neWRE8gRveVBaatz/projectcss
import sty from "./PlasmicBackups.module.css"; // plasmic-import: RX5xG043iUMC/css

import CloudPlusSvgIcon from "./icons/PlasmicIcon__CloudPlusSvg"; // plasmic-import: uOmgSDCdFDth/icon
import Icon19Icon from "./icons/PlasmicIcon__Icon19"; // plasmic-import: 6im6f-sFV6o1/icon

createPlasmicElementProxy;

export type PlasmicBackups__VariantMembers = {};
export type PlasmicBackups__VariantsArgs = {};
type VariantPropType = keyof PlasmicBackups__VariantsArgs;
export const PlasmicBackups__VariantProps = new Array<VariantPropType>();

export type PlasmicBackups__ArgsType = {};
type ArgPropType = keyof PlasmicBackups__ArgsType;
export const PlasmicBackups__ArgProps = new Array<ArgPropType>();

export type PlasmicBackups__OverridesType = {
  main?: Flex__<"div">;
  dashboard?: Flex__<typeof Dashboard>;
  pageInfo?: Flex__<typeof PageInfo>;
  welcomeBackToRhom?: Flex__<"div">;
  button?: Flex__<typeof Button>;
  svg?: Flex__<"svg">;
  section?: Flex__<"div">;
  customTable?: Flex__<typeof CustomTable>;
};

export interface DefaultBackupsProps {}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicBackups__RenderFunc(props: {
  variants: PlasmicBackups__VariantsArgs;
  args: PlasmicBackups__ArgsType;
  overrides: PlasmicBackups__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const $translator = usePlasmicTranslator?.();

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  return (
    <React.Fragment>
      <Head>
        <meta name="twitter:card" content="summary" />
        <title key="title">{PlasmicBackups.pageMetadata.title}</title>
        <meta
          key="og:title"
          property="og:title"
          content={PlasmicBackups.pageMetadata.title}
        />
        <meta
          key="twitter:title"
          name="twitter:title"
          content={PlasmicBackups.pageMetadata.title}
        />
        <meta
          key="description"
          name="description"
          content={PlasmicBackups.pageMetadata.description}
        />
        <meta
          key="og:description"
          property="og:description"
          content={PlasmicBackups.pageMetadata.description}
        />
        <meta
          key="twitter:description"
          name="twitter:description"
          content={PlasmicBackups.pageMetadata.description}
        />
      </Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div
        data-plasmic-name={"main"}
        data-plasmic-override={overrides.main}
        data-plasmic-root={true}
        data-plasmic-for-node={forNode}
        className={classNames(
          projectcss.all,
          projectcss.root_reset,
          projectcss.plasmic_default_styles,
          projectcss.plasmic_mixins,
          projectcss.plasmic_tokens,
          plasmic_antd_5_hostless_css.plasmic_tokens,
          plasmic_plasmic_rich_components_css.plasmic_tokens,
          sty.main
        )}
      >
        <Dashboard
          data-plasmic-name={"dashboard"}
          data-plasmic-override={overrides.dashboard}
          className={classNames("__wab_instance", sty.dashboard)}
          contentSection={
            <React.Fragment>
              <PageInfo
                data-plasmic-name={"pageInfo"}
                data-plasmic-override={overrides.pageInfo}
                action={
                  <Button
                    data-plasmic-name={"button"}
                    data-plasmic-override={overrides.button}
                    className={classNames("__wab_instance", sty.button)}
                    color={"green"}
                    shape={"rounded"}
                    showStartIcon={true}
                    size={"compact"}
                    startIcon={
                      <CloudPlusSvgIcon
                        data-plasmic-name={"svg"}
                        data-plasmic-override={overrides.svg}
                        className={classNames(projectcss.all, sty.svg)}
                        role={"img"}
                      />
                    }
                    submitsForm={false}
                  >
                    <Trans__>{"New Backup"}</Trans__>
                  </Button>
                }
                className={classNames("__wab_instance", sty.pageInfo)}
                description={
                  <div
                    data-plasmic-name={"welcomeBackToRhom"}
                    data-plasmic-override={overrides.welcomeBackToRhom}
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.welcomeBackToRhom
                    )}
                  >
                    <Trans__>
                      {"Manage and create backups, backup logs."}
                    </Trans__>
                  </div>
                }
                isAction={true}
              />

              <div
                data-plasmic-name={"section"}
                data-plasmic-override={overrides.section}
                className={classNames(projectcss.all, sty.section)}
              >
                <CustomTable
                  data-plasmic-name={"customTable"}
                  data-plasmic-override={overrides.customTable}
                  className={classNames("__wab_instance", sty.customTable)}
                />
              </div>
            </React.Fragment>
          }
        />
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  main: [
    "main",
    "dashboard",
    "pageInfo",
    "welcomeBackToRhom",
    "button",
    "svg",
    "section",
    "customTable"
  ],
  dashboard: [
    "dashboard",
    "pageInfo",
    "welcomeBackToRhom",
    "button",
    "svg",
    "section",
    "customTable"
  ],
  pageInfo: ["pageInfo", "welcomeBackToRhom", "button", "svg"],
  welcomeBackToRhom: ["welcomeBackToRhom"],
  button: ["button", "svg"],
  svg: ["svg"],
  section: ["section", "customTable"],
  customTable: ["customTable"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  main: "div";
  dashboard: typeof Dashboard;
  pageInfo: typeof PageInfo;
  welcomeBackToRhom: "div";
  button: typeof Button;
  svg: "svg";
  section: "div";
  customTable: typeof CustomTable;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicBackups__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicBackups__VariantsArgs;
    args?: PlasmicBackups__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicBackups__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicBackups__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicBackups__ArgProps,
          internalVariantPropNames: PlasmicBackups__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicBackups__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "main") {
    func.displayName = "PlasmicBackups";
  } else {
    func.displayName = `PlasmicBackups.${nodeName}`;
  }
  return func;
}

export const PlasmicBackups = Object.assign(
  // Top-level PlasmicBackups renders the root element
  makeNodeComponent("main"),
  {
    // Helper components rendering sub-elements
    dashboard: makeNodeComponent("dashboard"),
    pageInfo: makeNodeComponent("pageInfo"),
    welcomeBackToRhom: makeNodeComponent("welcomeBackToRhom"),
    button: makeNodeComponent("button"),
    svg: makeNodeComponent("svg"),
    section: makeNodeComponent("section"),
    customTable: makeNodeComponent("customTable"),

    // Metadata about props expected for PlasmicBackups
    internalVariantProps: PlasmicBackups__VariantProps,
    internalArgProps: PlasmicBackups__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "Backups",
      description: "Manage and create backups, backup logs.",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicBackups;
/* prettier-ignore-end */
