// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: qFgf32neWRE8gRveVBaatz
// Component: QNZjHdReq39P

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import Dashboard from "../../Dashboard"; // plasmic-import: xrHIipmjGkuW/component
import PageInfo from "../../PageInfo"; // plasmic-import: -5yQM3hZscI3/component
import Button from "../../Button"; // plasmic-import: JRPPbMhYptfo/component
import CtTabs from "../../CtTabs"; // plasmic-import: 2l3jZIBKayAy/component
import { TabsContainer } from "@plasmicpkgs/plasmic-tabs";
import { TabButton } from "@plasmicpkgs/plasmic-tabs";
import TabButton2 from "../../TabButton"; // plasmic-import: TAXiLlfQD5MN/component
import { TabUnderline } from "@plasmicpkgs/plasmic-tabs";
import { TabContent } from "@plasmicpkgs/plasmic-tabs";
import CustomTable from "../../CustomTable"; // plasmic-import: SyYLCRWlXb0u/component

import "@plasmicapp/react-web/lib/plasmic.css";

import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import plasmic_plasmic_rich_components_css from "../plasmic_rich_components/plasmic.module.css"; // plasmic-import: jkU633o1Cz7HrJdwdxhVHk/projectcss
import projectcss from "./plasmic.module.css"; // plasmic-import: qFgf32neWRE8gRveVBaatz/projectcss
import sty from "./PlasmicSubmissions.module.css"; // plasmic-import: QNZjHdReq39P/css

import PlusSvgIcon from "./icons/PlasmicIcon__PlusSvg"; // plasmic-import: qKMzzxYWCT9r/icon
import Icon19Icon from "./icons/PlasmicIcon__Icon19"; // plasmic-import: 6im6f-sFV6o1/icon
import CheckSvgIcon from "./icons/PlasmicIcon__CheckSvg"; // plasmic-import: 9Xy14f7tX9Ax/icon

createPlasmicElementProxy;

export type PlasmicSubmissions__VariantMembers = {};
export type PlasmicSubmissions__VariantsArgs = {};
type VariantPropType = keyof PlasmicSubmissions__VariantsArgs;
export const PlasmicSubmissions__VariantProps = new Array<VariantPropType>();

export type PlasmicSubmissions__ArgsType = {};
type ArgPropType = keyof PlasmicSubmissions__ArgsType;
export const PlasmicSubmissions__ArgProps = new Array<ArgPropType>();

export type PlasmicSubmissions__OverridesType = {
  home?: Flex__<"div">;
  dashboard?: Flex__<typeof Dashboard>;
  pageInfo?: Flex__<typeof PageInfo>;
  welcomeBackToRhom?: Flex__<"div">;
  section?: Flex__<"div">;
  ctTabs?: Flex__<typeof CtTabs>;
  tabsContainer?: Flex__<typeof TabsContainer>;
  tabBody?: Flex__<"div">;
  header?: Flex__<"div">;
  tabUnderline?: Flex__<typeof TabUnderline>;
  content?: Flex__<"div">;
};

export interface DefaultSubmissionsProps {}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicSubmissions__RenderFunc(props: {
  variants: PlasmicSubmissions__VariantsArgs;
  args: PlasmicSubmissions__ArgsType;
  overrides: PlasmicSubmissions__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const $translator = usePlasmicTranslator?.();

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  return (
    <React.Fragment>
      <Head>
        <meta name="twitter:card" content="summary" />
        <title key="title">{PlasmicSubmissions.pageMetadata.title}</title>
        <meta
          key="og:title"
          property="og:title"
          content={PlasmicSubmissions.pageMetadata.title}
        />
        <meta
          key="twitter:title"
          name="twitter:title"
          content={PlasmicSubmissions.pageMetadata.title}
        />
        <meta
          key="description"
          name="description"
          content={PlasmicSubmissions.pageMetadata.description}
        />
        <meta
          key="og:description"
          property="og:description"
          content={PlasmicSubmissions.pageMetadata.description}
        />
        <meta
          key="twitter:description"
          name="twitter:description"
          content={PlasmicSubmissions.pageMetadata.description}
        />
      </Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div
        data-plasmic-name={"home"}
        data-plasmic-override={overrides.home}
        data-plasmic-root={true}
        data-plasmic-for-node={forNode}
        className={classNames(
          projectcss.all,
          projectcss.root_reset,
          projectcss.plasmic_default_styles,
          projectcss.plasmic_mixins,
          projectcss.plasmic_tokens,
          plasmic_antd_5_hostless_css.plasmic_tokens,
          plasmic_plasmic_rich_components_css.plasmic_tokens,
          sty.home
        )}
      >
        <Dashboard
          data-plasmic-name={"dashboard"}
          data-plasmic-override={overrides.dashboard}
          className={classNames("__wab_instance", sty.dashboard)}
          contentSection={
            <React.Fragment>
              <PageInfo
                data-plasmic-name={"pageInfo"}
                data-plasmic-override={overrides.pageInfo}
                className={classNames("__wab_instance", sty.pageInfo)}
                description={
                  <div
                    data-plasmic-name={"welcomeBackToRhom"}
                    data-plasmic-override={overrides.welcomeBackToRhom}
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.welcomeBackToRhom
                    )}
                  >
                    <Trans__>{"Track user submissions from forms."}</Trans__>
                  </div>
                }
              />

              <div
                data-plasmic-name={"section"}
                data-plasmic-override={overrides.section}
                className={classNames(projectcss.all, sty.section)}
              >
                <CtTabs
                  data-plasmic-name={"ctTabs"}
                  data-plasmic-override={overrides.ctTabs}
                  className={classNames("__wab_instance", sty.ctTabs)}
                >
                  <TabsContainer
                    data-plasmic-name={"tabsContainer"}
                    data-plasmic-override={overrides.tabsContainer}
                    className={classNames("__wab_instance", sty.tabsContainer)}
                    initialKey={"tab1"}
                    previewAll={false}
                  >
                    <DataCtxReader__>
                      {$ctx => (
                        <Stack__
                          as={"div"}
                          data-plasmic-name={"tabBody"}
                          data-plasmic-override={overrides.tabBody}
                          hasGap={true}
                          className={classNames(projectcss.all, sty.tabBody)}
                        >
                          <div
                            data-plasmic-name={"header"}
                            data-plasmic-override={overrides.header}
                            className={classNames(projectcss.all, sty.header)}
                          >
                            <TabButton
                              className={classNames(
                                "__wab_instance",
                                sty.tabButton__yI7W4
                              )}
                              tabKey={"tab1"}
                            >
                              <TabButton2
                                className={classNames(
                                  "__wab_instance",
                                  sty.tabButton__aiDpz
                                )}
                                label={<Trans__>{"All"}</Trans__>}
                                size={"compact"}
                              />
                            </TabButton>
                            <TabButton
                              className={classNames(
                                "__wab_instance",
                                sty.tabButton__wpBmH
                              )}
                              tabKey={"tab2"}
                            >
                              <TabButton2
                                className={classNames(
                                  "__wab_instance",
                                  sty.tabButton___0JoSj
                                )}
                                label={<Trans__>{"Unread"}</Trans__>}
                                size={"compact"}
                              />
                            </TabButton>
                            <TabButton
                              className={classNames(
                                "__wab_instance",
                                sty.tabButton__xA8O1
                              )}
                              tabKey={"tab3"}
                            >
                              <TabButton2
                                className={classNames(
                                  "__wab_instance",
                                  sty.tabButton__l0FVu
                                )}
                                label={<Trans__>{"Read"}</Trans__>}
                                size={"compact"}
                              />
                            </TabButton>
                            <TabUnderline
                              data-plasmic-name={"tabUnderline"}
                              data-plasmic-override={overrides.tabUnderline}
                              className={classNames(
                                "__wab_instance",
                                sty.tabUnderline
                              )}
                            />
                          </div>
                          <div
                            data-plasmic-name={"content"}
                            data-plasmic-override={overrides.content}
                            className={classNames(projectcss.all, sty.content)}
                          >
                            <TabContent
                              className={classNames(
                                "__wab_instance",
                                sty.tabContent__lAhgL
                              )}
                              tabKey={"tab1"}
                            >
                              <CustomTable
                                className={classNames(
                                  "__wab_instance",
                                  sty.customTable__kJr6P
                                )}
                              />
                            </TabContent>
                            <TabContent
                              className={classNames(
                                "__wab_instance",
                                sty.tabContent__gnLk
                              )}
                              tabKey={"tab2"}
                            >
                              <CustomTable
                                className={classNames(
                                  "__wab_instance",
                                  sty.customTable__obHgX
                                )}
                              />
                            </TabContent>
                            <TabContent
                              className={classNames(
                                "__wab_instance",
                                sty.tabContent__edLf3
                              )}
                              tabKey={"tab3"}
                            >
                              <CustomTable
                                className={classNames(
                                  "__wab_instance",
                                  sty.customTable__b5Pa6
                                )}
                              />
                            </TabContent>
                          </div>
                        </Stack__>
                      )}
                    </DataCtxReader__>
                  </TabsContainer>
                </CtTabs>
              </div>
            </React.Fragment>
          }
        />
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  home: [
    "home",
    "dashboard",
    "pageInfo",
    "welcomeBackToRhom",
    "section",
    "ctTabs",
    "tabsContainer",
    "tabBody",
    "header",
    "tabUnderline",
    "content"
  ],
  dashboard: [
    "dashboard",
    "pageInfo",
    "welcomeBackToRhom",
    "section",
    "ctTabs",
    "tabsContainer",
    "tabBody",
    "header",
    "tabUnderline",
    "content"
  ],
  pageInfo: ["pageInfo", "welcomeBackToRhom"],
  welcomeBackToRhom: ["welcomeBackToRhom"],
  section: [
    "section",
    "ctTabs",
    "tabsContainer",
    "tabBody",
    "header",
    "tabUnderline",
    "content"
  ],
  ctTabs: [
    "ctTabs",
    "tabsContainer",
    "tabBody",
    "header",
    "tabUnderline",
    "content"
  ],
  tabsContainer: [
    "tabsContainer",
    "tabBody",
    "header",
    "tabUnderline",
    "content"
  ],
  tabBody: ["tabBody", "header", "tabUnderline", "content"],
  header: ["header", "tabUnderline"],
  tabUnderline: ["tabUnderline"],
  content: ["content"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  home: "div";
  dashboard: typeof Dashboard;
  pageInfo: typeof PageInfo;
  welcomeBackToRhom: "div";
  section: "div";
  ctTabs: typeof CtTabs;
  tabsContainer: typeof TabsContainer;
  tabBody: "div";
  header: "div";
  tabUnderline: typeof TabUnderline;
  content: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicSubmissions__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicSubmissions__VariantsArgs;
    args?: PlasmicSubmissions__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicSubmissions__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicSubmissions__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicSubmissions__ArgProps,
          internalVariantPropNames: PlasmicSubmissions__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicSubmissions__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "home") {
    func.displayName = "PlasmicSubmissions";
  } else {
    func.displayName = `PlasmicSubmissions.${nodeName}`;
  }
  return func;
}

export const PlasmicSubmissions = Object.assign(
  // Top-level PlasmicSubmissions renders the root element
  makeNodeComponent("home"),
  {
    // Helper components rendering sub-elements
    dashboard: makeNodeComponent("dashboard"),
    pageInfo: makeNodeComponent("pageInfo"),
    welcomeBackToRhom: makeNodeComponent("welcomeBackToRhom"),
    section: makeNodeComponent("section"),
    ctTabs: makeNodeComponent("ctTabs"),
    tabsContainer: makeNodeComponent("tabsContainer"),
    tabBody: makeNodeComponent("tabBody"),
    header: makeNodeComponent("header"),
    tabUnderline: makeNodeComponent("tabUnderline"),
    content: makeNodeComponent("content"),

    // Metadata about props expected for PlasmicSubmissions
    internalVariantProps: PlasmicSubmissions__VariantProps,
    internalArgProps: PlasmicSubmissions__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "Submissions",
      description: "Track user submissions from forms.",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicSubmissions;
/* prettier-ignore-end */
