// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: qFgf32neWRE8gRveVBaatz
// Component: V-WhOu_9VTgo

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import "@plasmicapp/react-web/lib/plasmic.css";

import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import plasmic_plasmic_rich_components_css from "../plasmic_rich_components/plasmic.module.css"; // plasmic-import: jkU633o1Cz7HrJdwdxhVHk/projectcss
import projectcss from "./plasmic.module.css"; // plasmic-import: qFgf32neWRE8gRveVBaatz/projectcss
import sty from "./PlasmicCtMoreButton.module.css"; // plasmic-import: V-WhOu_9VTgo/css

import Icon38Icon from "./icons/PlasmicIcon__Icon38"; // plasmic-import: -T_ZDw4_KsiR/icon

createPlasmicElementProxy;

export type PlasmicCtMoreButton__VariantMembers = {};
export type PlasmicCtMoreButton__VariantsArgs = {};
type VariantPropType = keyof PlasmicCtMoreButton__VariantsArgs;
export const PlasmicCtMoreButton__VariantProps = new Array<VariantPropType>();

export type PlasmicCtMoreButton__ArgsType = {};
type ArgPropType = keyof PlasmicCtMoreButton__ArgsType;
export const PlasmicCtMoreButton__ArgProps = new Array<ArgPropType>();

export type PlasmicCtMoreButton__OverridesType = {
  moreButtonIcon?: Flex__<"svg">;
};

export interface DefaultCtMoreButtonProps {
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicCtMoreButton__RenderFunc(props: {
  variants: PlasmicCtMoreButton__VariantsArgs;
  args: PlasmicCtMoreButton__ArgsType;
  overrides: PlasmicCtMoreButton__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const $translator = usePlasmicTranslator?.();

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  return (
    <Icon38Icon
      data-plasmic-name={"moreButtonIcon"}
      data-plasmic-override={overrides.moreButtonIcon}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        plasmic_antd_5_hostless_css.plasmic_tokens,
        plasmic_plasmic_rich_components_css.plasmic_tokens,
        sty.moreButtonIcon
      )}
      role={"img"}
    />
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  moreButtonIcon: ["moreButtonIcon"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  moreButtonIcon: "svg";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicCtMoreButton__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicCtMoreButton__VariantsArgs;
    args?: PlasmicCtMoreButton__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicCtMoreButton__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicCtMoreButton__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicCtMoreButton__ArgProps,
          internalVariantPropNames: PlasmicCtMoreButton__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicCtMoreButton__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "moreButtonIcon") {
    func.displayName = "PlasmicCtMoreButton";
  } else {
    func.displayName = `PlasmicCtMoreButton.${nodeName}`;
  }
  return func;
}

export const PlasmicCtMoreButton = Object.assign(
  // Top-level PlasmicCtMoreButton renders the root element
  makeNodeComponent("moreButtonIcon"),
  {
    // Helper components rendering sub-elements

    // Metadata about props expected for PlasmicCtMoreButton
    internalVariantProps: PlasmicCtMoreButton__VariantProps,
    internalArgProps: PlasmicCtMoreButton__ArgProps
  }
);

export default PlasmicCtMoreButton;
/* prettier-ignore-end */
